CREATE TABLE CatalogueBook (
  Id INTEGER PRIMARY KEY IDENTITY(1,1),
  Isbn VARCHAR(100) NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Author VARCHAR(100) NOT NULL);


CREATE TABLE CatalogueBookInstance (
  Id INTEGER PRIMARY KEY IDENTITY(1,1),
  Isbn VARCHAR(100) NOT NULL,
  Book_id UNIQUEIDENTIFIER  NOT NULL);

CREATE SEQUENCE CatalogueBookSeq
 AS INT
 START WITH 1
 INCREMENT BY 1;

CREATE SEQUENCE CatalogueBookInstanceSeq
 AS INT
 START WITH 1
 INCREMENT BY 1;

CREATE TABLE BookDatabaseEntity (
  Id INTEGER PRIMARY KEY IDENTITY(1,1),
  BookId UNIQUEIDENTIFIER UNIQUE,
  BookType VARCHAR(100) NOT NULL,
  BookState VARCHAR(100) NOT NULL,
  AvailableAtBranch UNIQUEIDENTIFIER,
  OnHoldAtBranch UNIQUEIDENTIFIER,
  OnHoldByPatron UNIQUEIDENTIFIER,
  CheckedOutAtBranch UNIQUEIDENTIFIER,
  CheckedOutByPatron UNIQUEIDENTIFIER,
  OnHoldTill DATETIME,
  Version INTEGER);
  
CREATE SEQUENCE BookDatabaseEntitySeq
 AS INT
 START WITH 1
 INCREMENT BY 1;


CREATE TABLE PatronDatabaseEntity (Id INTEGER PRIMARY KEY IDENTITY(1,1), PatronType VARCHAR(100) NOT NULL, PatronId UNIQUEIDENTIFIER UNIQUE);

CREATE TABLE HoldDatabaseEntity (
  Id INTEGER PRIMARY KEY IDENTITY(1,1),
  BookId UNIQUEIDENTIFIER NOT NULL,
  PatronId UNIQUEIDENTIFIER NOT NULL,
  LibraryBranchId UNIQUEIDENTIFIER NOT NULL,
  PatronDatabaseEntity INTEGER NOT NULL,
  Till DATETIME NOT NULL,
  CONSTRAINT [FK_HoldDatabaseEntity_PatronDatabaseEntity] FOREIGN KEY (PatronDatabaseEntity) REFERENCES PatronDatabaseEntity ([Id]));