FROM mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1-buster AS build
WORKDIR /src

COPY . .
RUN dotnet restore "DatabaseMigrator/DatabaseMigrator.csproj"

WORKDIR "/src"
RUN dotnet build "DatabaseMigrator/DatabaseMigrator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DatabaseMigrator/DatabaseMigrator.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ADD entrypoint_DatabaseMigrator.sh /
ADD migrations /migrations/

# Copy wait-for-it.sh into our image
#COPY wait-for-it.sh wait-for-it.sh
# Make it executable, in Linux
#RUN chmod +x wait-for-it.sh

ENTRYPOINT ["/bin/bash", "/entrypoint_DatabaseMigrator.sh"]
